[tools]
aube = "latest"
biome = "latest"
cspell = "latest"
dprint = "latest"
go = "latest"
just = "latest"
node = "lts"
"pipx:fonttools" = "latest"
"pipx:ocrmypdf" = "latest"
pnpm = "latest"
python = "latest"
rumdl = "latest"
shellcheck = "latest"
shfmt = "latest"
typos = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "node", "pnpm"]
auto_install = false
not_found_auto_install = false

[settings.python]
uv_venv_auto = "source"

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "aube"

[env]
VISUAL = { default = "code --wait" }
EDITOR = { default = "code --wait" }
LANG = { default = "zh_CN.UTF-8" }
PNPM_CONFIG_PM_ON_FAIL = "ignore"
NODE_USE_SYSTEM_CA = 1
