[tools]
aube = "latest"
go = "latest"
node = "lts"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:cspell" = "latest"
"pipx:docx2pdf" = "latest"
"pipx:fonttools" = "latest"
"pipx:markitdown" = { version = "latest", extras = "all", uvx_args = "-w markitdown-ocr -w openai" }
"pipx:sqlfluff" = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]

[settings.python]
uv_venv_auto = "source"

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "aube"
