[Diagnostics.CodeAnalysis.SuppressMessageAttribute(
    'PSAvoidUsingInvokeExpression',
    '',
    Justification = 'Executes initialization code generated by trusted CLI tools.'
)]
param()

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::InputEncoding = [System.Text.Encoding]::UTF8

# Modules
Set-PSReadLineOption -Colors @{ Selection = $PSStyle.Reverse }
Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
Import-Module PSFzf
Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r'
Import-Module ScriptRunner
Enable-ScriptPicker

# Tools
mise activate pwsh | Out-String | Invoke-Expression
starship init powershell | Out-String | Invoke-Expression
zoxide init powershell | Out-String | Invoke-Expression
carapace _carapace powershell | Out-String | Invoke-Expression

# Windows Terminal shell integration
$Global:__OriginalPrompt = $function:Prompt
$Global:__TerminalLastHistoryId = -1

$PromptStart = "`e]133;A`a"
$PromptEnd = "`e]133;B`a"
$CommandEnd = "`e]133;D`a"

function Get-TerminalLastExitCode {
    param(
        [bool]$CommandSucceeded,
        [int]$NativeExitCode,
        $LastHistory
    )

    if ($CommandSucceeded) {
        return 0
    }

    $isPowerShellError =
    $null -ne $LastHistory -and
    $Error.Count -gt 0 -and
    $Error[0].InvocationInfo.HistoryId -eq $LastHistory.Id

    if ($isPowerShellError) {
        return -1 # PowerShell errors do not have a native process exit code.
    }

    return $NativeExitCode
}

function Global:prompt {
    # Capture status before any other statement can overwrite it.
    $commandSucceeded = $?
    $nativeExitCode = $LASTEXITCODE
    $lastHistory = Get-History -Count 1
    $output = ""

    # Mark the end of the previous command.
    if ($Global:__TerminalLastHistoryId -ne -1) {
        $hasNewHistoryEntry =
        $null -ne $lastHistory -and
        $lastHistory.Id -ne $Global:__TerminalLastHistoryId

        if ($hasNewHistoryEntry) {
            $exitCode = Get-TerminalLastExitCode -CommandSucceeded $commandSucceeded -NativeExitCode $nativeExitCode -LastHistory $lastHistory
            $output += "`e]133;D;$exitCode`a"
        }
        else {
            $output += $CommandEnd
        }
    }

    $output += $PromptStart
    $cwd = $ExecutionContext.SessionState.Path.CurrentLocation
    $output += "`e]9;9;`"$cwd`"`a"

    # Starship reads $? on entry. Restore failure without adding to $Error.
    if (-not $commandSucceeded) {
        Write-Error '' -ErrorAction Ignore
    }
    $output += $Global:__OriginalPrompt.Invoke()
    $output += $PromptEnd

    # Zero means the initial prompt was shown, before any command was run.
    $Global:__TerminalLastHistoryId = if ($null -ne $lastHistory) { $lastHistory.Id } else { 0 }

    return $output
}

# Completions
# just --completions powershell | Out-String | Invoke-Expression
# pnpm completion pwsh | Out-String | Invoke-Expression
# uv generate-shell-completion powershell | Out-String | Invoke-Expression

# fastfetch
