[Diagnostics.CodeAnalysis.SuppressMessageAttribute(
    'PSAvoidUsingInvokeExpression',
    '',
    Justification = 'Executes initialization code generated by trusted CLI tools.'
)]
param()

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::InputEncoding = [System.Text.Encoding]::UTF8

# Modules
Set-PSReadLineOption -Colors @{ Selection = $PSStyle.Reverse }
Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
Import-Module PSFzf
Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r'
# Import-Module PSCompletions

# Tools
mise activate pwsh | Out-String | Invoke-Expression
starship init powershell | Out-String | Invoke-Expression
zoxide init powershell | Out-String | Invoke-Expression
carapace _carapace powershell | Out-String | Invoke-Expression

# Completions
# just --completions powershell | Out-String | Invoke-Expression
# pnpm completion pwsh | Out-String | Invoke-Expression
# uv generate-shell-completion powershell | Out-String | Invoke-Expression

# fastfetch
