[helpers]

[settings]
default_target_type = "automatic"

[bash.files]
"bash/ibat.sh" = "~/.local/bin/ibat.sh"
"bash/irg.sh" = "~/.local/bin/irg.sh"
"bash/isd.sh" = "~/.local/bin/isd.sh"
"bash/jq-path.sh" = "~/.local/bin/jq-path.sh"
"bash/jq-content.sh" = "~/.local/bin/jq-content.sh"

[conda.files]
"conda.yaml" = "~/.condarc"

[fastfetch.files]
"fastfetch/fastfetch.jsonc" = "~/.config/fastfetch/config.jsonc"
"fastfetch/sakiko.txt" = "~/.local/share/fastfetch/sakiko.txt"

[git.variables]
git_name = ""
git_email = ""

[pixi.files]
"pixi/pixi.toml" = "~/.pixi/config.toml"
"pixi/global.toml" = "~/.pixi/manifests/pixi-global.toml"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[uv.files]
"uv.toml" = "~/.config/uv/uv.toml"

[vim.files]
"vim.vim" = "~/.vimrc"

[vscode.files]
"vscode/global/settings.jsonc" = "~/.config/Code/User/settings.json"
