[helpers]

[settings]
default_target_type = "automatic"

[agents.files]
"agents/skills" = { target = "~/.agents/skills", type = "symbolic", recurse = false }

[bash.files]
"bash/scripts" = "~/.local/bin"

[bat.files]
"bat/config.txt" = "$BAT_CONFIG_DIR/config"

[pi.files]
"pi/themes" = "~/.pi/agent/themes"

[codex.files]
"codex/rules" = "~/.codex/rules"
"codex/pets" = { target = "~/.codex/pets", type = "symbolic", recurse = false }
"codex/scripts" = "~/.local/bin"

[conda.files]
"conda/config.yaml" = "~/.condarc"

[fastfetch.files]
"fastfetch/config.jsonc" = "~/.config/fastfetch/config.jsonc"
"fastfetch/logos" = "~/.local/share/fastfetch/logos"

[git.files]
"git/config.ini" = "~/.gitconfig"
"git/scripts" = "~/.local/bin"
[git.variables]
git_name = ""
git_email = ""

[npm.files]
"npm/config.ini" = "~/.npmrc"

[pixi.files]
"pixi/pixi.toml" = "$PIXI_HOME/config.toml"
"pixi/global.toml" = "$PIXI_HOME/manifests/pixi-global.toml"

[pnpm.files]
"pnpm/config.yaml" = "~/.config/pnpm/config.yaml"
[pnpm.variables]
pnpm_store = "~/AppData/Local/pnpm/store"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[uv.files]
"uv/uv.toml" = "~/.config/uv/uv.toml"

[vim.files]
"vim/vim.vim" = "~/.vimrc"

[vscode.files]
"vscode/profiles/global/keybindings.jsonc" = "~/.config/Code/User/keybindings.json"
"vscode/profiles/global/settings.jsonc" = "~/.config/Code/User/settings.json"
"vscode/profiles/global/snippets" = "~/.config/Code/User/snippets"
"vscode/scripts" = "~/.local/bin"
