includes = [".dotter/windows.toml"]
packages = [
  "bash",
  "conda",
  "fastfetch",
  "git",
  "mise",
  "npm",
  "pixi",
  "starship",
  "uv",
  "vim",
  "vscode",
  "zsh",
  "windows",
]

[files]

[variables]
git_name = "Your git name"
git_email = "Your git email"

git_root = "path/to/git"
msys_root = "path/to/msys"
scoop_root = "path/to/scoop"
