includes = [".dotter/windows.toml"]
packages = [
  "agents",
  "bash",
  "bat",
  "codex",
  "conda",
  "fastfetch",
  "git",
  "mise",
  "neovim",
  "npm",
  "pi",
  "pixi",
  "pnpm",
  "starship",
  "uv",
  "vim",
  "vscode",
  "zsh",
  "windows",
]

[files]
"vscode/profiles/conf/settings.jsonc" = "~/AppData/Roaming/Code/User/profiles/conf_id/settings.json"
"vscode/profiles/doc/settings.jsonc" = "~/AppData/Roaming/Code/User/profiles/doc_id/settings.json"
"vscode/profiles/emb/settings.jsonc" = "~/AppData/Roaming/Code/User/profiles/emb_id/settings.json"
"vscode/profiles/game/settings.jsonc" = "~/AppData/Roaming/Code/User/profiles/game_id/settings.json"
"vscode/profiles/sci/settings.jsonc" = "~/AppData/Roaming/Code/User/profiles/sci_id/settings.json"
"vscode/profiles/sys/settings.jsonc" = "~/AppData/Roaming/Code/User/profiles/sys_id/settings.json"
"vscode/profiles/web/settings.jsonc" = "~/AppData/Roaming/Code/User/profiles/web_id/settings.json"

[variables]
git_name = "Your git name"
git_email = "Your git email"

pnpm_store = "path/to/pnpm-store"
scoop_root = "path/to/scoop"
