[bash.files]
"bash/windows.bash" = "~/.bashrc"

[mise.files]
"mise/windows.toml" = "~/.config/mise/config.toml"

[uv.files]
"uv.toml" = "~/AppData/Roaming/uv/uv.toml"

[vscode.files]
"vscode/global/settings.jsonc" = "~/AppData/Roaming/Code/User/settings.json"
"vscode/global/snippets" = "~/AppData/Roaming/Code/User/snippets"
"vscode/Find-VscodeDuplicateExtensions.ps1" = "~/.local/bin/Find-VscodeDuplicateExtensions.ps1"

[zsh.files]
"zsh/windows.sh" = "~/.zshrc"

[windows]
depends = ["pwsh", "scoop", "wt"]

[windows.variables]
git_root = "C:/Program Files/Git"
msys_root = "C:/msys64"

[pwsh.files]
"pwsh/pwsh.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"pwsh/scripts" = "~/.local/bin"

[scoop.files]
"scoop/scoop.json" = "~/.config/scoop/config.json"
"scoop/scripts" = "~/.local/bin"

[scoop.variables]
scoop_root = "~/scoop"

[wt.files]
"wt/wt.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
"wt/scripts" = "~/.local/bin"
