[bash.files]
"bash/windows.bash" = "~/.bashrc"

[mise.files]
"mise/windows.toml" = "~/.config/mise/config.toml"

[pnpm.files]
"pnpm.yaml" = "~/AppData/Local/pnpm/config/config.yaml"

[uv.files]
"uv.toml" = "~/AppData/Roaming/uv/uv.toml"

[vscode.files]
"vscode/profiles/global/keybindings.jsonc" = "~/AppData/Roaming/Code/User/keybindings.json"
"vscode/profiles/global/settings.jsonc" = "~/AppData/Roaming/Code/User/settings.json"
"vscode/profiles/global/snippets" = "~/AppData/Roaming/Code/User/snippets"

[zsh.files]
"zsh/windows.zsh" = "~/.zshrc"

[windows]
depends = ["msys", "pwsh", "scoop", "wt"]

[windows.variables]
git_root = "C:/Program Files/Git"

[msys.files]
"msys/nsswitch.conf" = "C:/msys64/etc/nsswitch.conf"

[msys.variables]
msys_root = "C:/msys64"

[pwsh.files]
"pwsh/pwsh.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"pwsh/scripts" = "~/.local/bin"

[scoop.files]
"scoop/scoop.json" = "~/.config/scoop/config.json"
"scoop/scripts" = "~/.local/bin"

[scoop.variables]
scoop_root = "~/scoop"

[wt.files]
"wt/wt.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
"wt/scripts" = "~/.local/bin"
